export default function getExampleResult() {
  return {
    maxVotes: 550782,
    totalVotes: 5612101,
    amountProposals: 21,
    overallRequestedFunding: 235301,
    fundedProposals: [
      {
        id: 'e77922D6D3',
        title: 'Data Whale',
        project: {
          id: 'b7f459cFF3',
          title: 'Data Whale',
          completedProposals: 7,
        },
        requestedFunding: 18500,
        receivedFunding: 18500,
        yesVotes: 550782,
        noVotes: 0,
        effectiveVotes: 550782,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'C98B34d38E',
        title: 'DataUnion Foundation',
        project: {
          id: 'ee4bCd09EC',
          title: 'DataUnion Foundation',
          completedProposals: 7,
        },
        requestedFunding: 32200,
        receivedFunding: 32200,
        yesVotes: 366926,
        noVotes: 39,
        effectiveVotes: 366887,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'A9B76cEaee',
        title: 'Ocean Pearl',
        project: {
          id: '3Df03dB5dD',
          title: 'Ocean Pearl',
          completedProposals: 4,
          logoUrl:
            'https://d2ap5e9vgx7wei.cloudfront.net/3Df03dB5dD-6f76F3bBF3.png',
        },
        requestedFunding: 20000,
        receivedFunding: 20000,
        yesVotes: 272282,
        noVotes: 38,
        effectiveVotes: 272244,
        tags: ['dao'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'EAE3c1Bbcc',
        title: 'RugPullIndex',
        project: {
          id: 'FaE6CBc239',
          title: 'RugPullIndex',
          completedProposals: 9,
        },
        requestedFunding: 17039,
        receivedFunding: 17039,
        yesVotes: 264246,
        noVotes: 0,
        effectiveVotes: 264246,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: '521e6EB04F',
        title: 'nCight',
        project: {
          id: '8F451d6faa',
          title: 'nCight',
          completedProposals: 1,
        },
        requestedFunding: 3000,
        receivedFunding: 3000,
        yesVotes: 282479,
        noVotes: 46617,
        effectiveVotes: 235862,
        tags: ['buildAndIntegrate', 'earmark'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        isEarmarked: true,
        earmarkType: 'newGeneral',
      },
      {
        id: '38cdDdB9AF',
        title: 'TokenSPICE',
        project: {
          id: 'ebE9f1E22C',
          title: 'TokenSPICE',
          completedProposals: 2,
        },
        requestedFunding: 10000,
        receivedFunding: 10000,
        yesVotes: 227946,
        noVotes: 0,
        effectiveVotes: 227946,
        tags: ['coreSoftware'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'Ddcee7B43d',
        title: 'Evotegra',
        project: {
          id: 'a44Da24bdD',
          title: 'Evotegra',
          completedProposals: 4,
        },
        requestedFunding: 3000,
        receivedFunding: 3000,
        yesVotes: 220330,
        noVotes: 1324,
        effectiveVotes: 219006,
        tags: ['unleashData'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: '8A43bE16ae',
        title: 'Taurus Chain Network',
        project: {
          id: '7Adbebd2d6',
          title: 'Taurus Chain Network',
          completedProposals: 1,
        },
        requestedFunding: 3000,
        receivedFunding: 3000,
        yesVotes: 260293,
        noVotes: 47105,
        effectiveVotes: 213188,
        tags: ['buildAndIntegrate', 'earmark'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        isEarmarked: true,
        earmarkType: 'newGeneral',
      },
      {
        id: 'A8ea7CE2BB',
        title: 'Datalatte.ai',
        project: {
          id: '1bDE1eaF63',
          title: 'Datalatte.ai',
          completedProposals: 2,
        },
        requestedFunding: 10000,
        receivedFunding: 10000,
        yesVotes: 190751,
        noVotes: 67,
        effectiveVotes: 190684,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: '62a84d6725',
        title: 'Ocean Missions',
        project: {
          id: 'e6BfE2d94a',
          title: 'Ocean Missions',
          completedProposals: 3,
        },
        requestedFunding: 7061,
        receivedFunding: 7061,
        yesVotes: 152513,
        noVotes: 57,
        effectiveVotes: 152456,
        tags: ['outreach'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'f543dE6b16',
        title: 'Ocean Protocol Japan',
        project: {
          id: '87dE5eFC94',
          title: 'Ocean Protocol Japan',
          completedProposals: 2,
        },
        requestedFunding: 6000,
        receivedFunding: 6000,
        yesVotes: 134336,
        noVotes: 452,
        effectiveVotes: 133884,
        tags: ['outreach'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'a939b97Ce6',
        title: 'DATAPOGY',
        project: {
          id: 'aDad9d44F6',
          title: 'DATAPOGY',
          completedProposals: 1,
        },
        requestedFunding: 3000,
        receivedFunding: 3000,
        yesVotes: 91963,
        noVotes: 1263,
        effectiveVotes: 90700,
        tags: ['unleashData', 'earmark'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        isEarmarked: true,
        earmarkType: 'newGeneral',
      },
      {
        id: '6696733eBe',
        title: 'HealthLink',
        project: {
          id: 'F5e77BFF14',
          title: 'HealthLink',
          completedProposals: 2,
        },
        requestedFunding: 10000,
        receivedFunding: 10000,
        yesVotes: 184670,
        noVotes: 100019,
        effectiveVotes: 84651,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'eB11C1B093',
        title: 'Nigeria Community Building',
        project: {
          id: '2aACfeA7B8',
          title: 'Nigeria Community Building',
          completedProposals: 1,
        },
        requestedFunding: 3000,
        receivedFunding: 3000,
        yesVotes: 50611,
        noVotes: 1787,
        effectiveVotes: 48824,
        tags: ['outreach', 'earmark'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        isEarmarked: true,
        earmarkType: 'newOutreach',
      },
      {
        id: '78F1B49f6D',
        title: 'WorkPi',
        project: {
          id: '8eDBB8Cd06',
          title: 'WorkPi',
          completedProposals: 2,
        },
        requestedFunding: 1,
        receivedFunding: 1,
        yesVotes: 42100,
        noVotes: 0,
        effectiveVotes: 42100,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
      {
        id: 'b1918bD07f',
        title: 'Ocean Protocol Turkey Community',
        project: {
          id: '78894aeF35',
          title: 'Ocean Protocol Turkey Community',
          completedProposals: 1,
        },
        requestedFunding: 3000,
        receivedFunding: 3000,
        yesVotes: 28462,
        noVotes: 452,
        effectiveVotes: 28010,
        tags: ['outreach', 'earmark'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        isEarmarked: true,
        earmarkType: 'newOutreach',
      },
      {
        id: 'facd95D7B3',
        title: 'Algovera',
        project: {
          id: 'e91BaE35Ab',
          title: 'Algovera',
          completedProposals: 3,
        },
        requestedFunding: 20000,
        receivedFunding: 20000,
        yesVotes: 226517,
        noVotes: 200038,
        effectiveVotes: 26479,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
      },
    ],
    notFundedProposals: [
      {
        id: 'cd67a2F0fF',
        title: 'RAZ Finance',
        project: {
          id: 'bdFC0CF29F',
          title: 'RAZ Finance',
          completedProposals: 2,
        },
        requestedFunding: 20000,
        receivedFunding: 0,
        yesVotes: 33449,
        noVotes: 90424,
        effectiveVotes: -56975,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        neededVotes: 56976,
      },
      {
        id: '9F7713Bb9F',
        title: 'Duggie',
        project: {
          id: 'aBDc4Fc04C',
          title: 'Duggie',
          completedProposals: 1,
        },
        requestedFunding: 8500,
        receivedFunding: 0,
        yesVotes: 6629,
        noVotes: 67408,
        effectiveVotes: -60779,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        neededVotes: 60780,
      },
      {
        id: '89469FDA6D',
        title: 'VideoWiki',
        project: {
          id: '2D70109D8F',
          title: 'VideoWiki',
          completedProposals: 2,
        },
        requestedFunding: 20000,
        receivedFunding: 0,
        yesVotes: 251437,
        noVotes: 331546,
        effectiveVotes: -80109,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        neededVotes: 80110,
      },
      {
        id: '8A3e5eA98a',
        title: 'Posthuman AI',
        project: {
          id: 'AC3dadD08E',
          title: 'Posthuman AI',
          completedProposals: 4,
        },
        requestedFunding: 18000,
        receivedFunding: 0,
        yesVotes: 399903,
        noVotes: 484840,
        effectiveVotes: -84937,
        tags: ['buildAndIntegrate'],
        voteUrl:
          'https://snapshot.org/#/officialoceandao.eth/proposal/QmZRZNHuoQqpA1KCiNa9oMaxx3i6u2o32eqVxRC8vANfuC',
        neededVotes: 84938,
      },
    ],
    paymentOption: 'USD',
    overallFunding: 528658.425,
    earmarks: {
      newGeneral: {
        type: 'newGeneral',
        remainingFunding: 54468,
      },
      newOutreach: {
        type: 'newOutreach',
        remainingFunding: 25719,
      },
      coreTech: {
        type: 'coreTech',
        remainingFunding: 31719,
      },
    },
    status: 'votingFinished',
    voteStartDate: '2021-11-04T23:59:00.000Z',
    voteEndDate: '2021-11-08T23:59:00.000Z',
    round: 11,
    remainingGeneralFunding: 247951.42500000005,
  };
}
