<template>
  <NuxtLink
    v-if="isNuxtLink"
    :to="to"
    class="bounce-right flex items-center mt-6"
    :class="link"
  >
    <p :class="paragraph">
      <slot />
    </p>
    <span :class="icon" />
  </NuxtLink>
  <a
    v-else
    :href="to"
    target="_blank"
    rel="noopener noreferrer"
    class="bounce-right flex items-center mt-6"
    :class="link"
  >
    <p :class="paragraph">
      <slot />
    </p>
    <span :class="icon" />
  </a>
</template>

<script>
export default {
  name: 'AppLinkIconRight',
  props: {
    to: {
      type: String,
      required: true,
      default: () => '',
    },
    link: {
      type: String,
      default: () => 'text-primary',
    },
    paragraph: {
      type: String,
      default: () => 'mr-2',
    },
    icon: {
      type: String,
      default: () => 'mdi mdi-arrow-right text-md sm:text-lg',
    },
  },
  computed: {
    isNuxtLink() {
      if (this.to) {
        return this.to.substring(0, 1) === '/';
      }
      return false;
    },
  },
};
</script>

<style scoped lang="scss">
/* ----------------------------------------------
 * Generated by Animista on 2021-10-3 15:18:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@keyframes bounce-right {
  0%,
  20%,
  50%,
  80%,
  100% {
    -ms-transform: translateX(0);
    transform: translateX(0);
  }
  40% {
    -ms-transform: translateX(20px);
    transform: translateX(20px);
  }
  60% {
    -ms-transform: translateX(10px);
    transform: translateX(10px);
  }
}
.bounce-right:hover,
.bounce-right:focus {
  span {
    -webkit-animation: bounce-right 2s infinite both;
    animation: bounce-right 2s infinite both;
  }
}
</style>
