export default {
  data() {
    return {
      PROJECT_REQUIRED_OCEAN: 500,
      PROJECT_COUNT_MAX: 6,
      PROJECT_TITLE_MAX_LENGTH: 64,
      PROJECT_ONE_LINER_MAX_LENGTH: 128,
      PROJECT_DESCRIPTION_MAX_LENGTH: 2048,
      PROJECT_IMAGES_MAX_COUNT: 8,
      PROJECT_UPDATE_TITLE_MAX_LENGTH: 128,
      PROJECT_UPDATE_DESCRIPTION_MAX_LENGTH: 2048,
    };
  },
};
