export default {
  data() {
    return {
      PROJECT_REQUIRED_OCEAN: 500,
      PROJECT_TITLE_MAX_LENGTH: 80,
      PROJECT_ONE_LINER_MAX_LENGTH: 80,
      PROJECT_DESCRIPTION_MAX_LENGTH: 2048,
      PROJECT_IMAGES_MAX_COUNT: 8,
    };
  },
};
